export const THEMES = {
    light: {
        name: 'Light',
        bg: '#FAFAF8',
        header: '#FFFFFF',
        card: '#FFFFFF',
        border: '#f1f0ed',
        text: '#1c1917',
        textMuted: '#78716c',
        textSubtle: '#a8a29e',
        accent: '#1c1917',
        accentText: '#FFFFFF',
        swatch: '#FAFAF8',
        swatchBorder: '#e7e5e4',
    },
    dark: {
        name: 'Dark',
        bg: '#18181b',
        header: '#1f1f23',
        card: '#27272a',
        border: '#3f3f46',
        text: '#fafafa',
        textMuted: '#a1a1aa',
        textSubtle: '#71717a',
        accent: '#fafafa',
        accentText: '#18181b',
        swatch: '#27272a',
        swatchBorder: '#3f3f46',
    },
    dusk: {
        name: 'Dusk',
        bg: '#fdf6f0',
        header: '#fff8f3',
        card: '#fff8f3',
        border: '#fde8d8',
        text: '#431407',
        textMuted: '#9a3412',
        textSubtle: '#c2855a',
        accent: '#c2410c',
        accentText: '#FFFFFF',
        swatch: '#fb923c',
        swatchBorder: '#ea580c',
    },
    forest: {
        name: 'Forest',
        bg: '#f2f7f2',
        header: '#f7faf7',
        card: '#f7faf7',
        border: '#d1e7d1',
        text: '#14532d',
        textMuted: '#166534',
        textSubtle: '#4ade80',
        accent: '#15803d',
        accentText: '#FFFFFF',
        swatch: '#4ade80',
        swatchBorder: '#16a34a',
    },
    ocean: {
        name: 'Ocean',
        bg: '#f0f7ff',
        header: '#f5f9ff',
        card: '#f5f9ff',
        border: '#bfdbfe',
        text: '#1e3a5f',
        textMuted: '#1d4ed8',
        textSubtle: '#60a5fa',
        accent: '#1d4ed8',
        accentText: '#FFFFFF',
        swatch: '#60a5fa',
        swatchBorder: '#2563eb',
    },
}