### Get all tasks (authenticated)
GET http://localhost:3000/api/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlOWI1NWY3ZS1kNzIyLTRiZTgtYmFhNi1hOGRkODFmNTI3NGMiLCJpYXQiOjE3Nzc1NzkyOTQsImV4cCI6MTc3ODE4NDA5NH0.WlVyPXnTKhSxiBgqQu3AZHwYvJwL1yQlERZiPNRsJOY

### Create task (authenticated)
POST http://localhost:3000/api/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlOWI1NWY3ZS1kNzIyLTRiZTgtYmFhNi1hOGRkODFmNTI3NGMiLCJpYXQiOjE3Nzc1NzkyOTQsImV4cCI6MTc3ODE4NDA5NH0.WlVyPXnTKhSxiBgqQu3AZHwYvJwL1yQlERZiPNRsJOY
Content-Type: application/json

{
  "description": "My first authenticated task",
  "priority": "high"
}

### Delete task
DELETE http://localhost:3000/api/tasks/cf2b0858-4705-4b97-8db0-a450a12ede01

### Update task
PUT http://localhost:3000/api/tasks/fdfebb28-9eeb-4e3f-84b8-0e271051f3ac
Content-Type: application/json

{
  "description": "Updated description"
}

### Update task status
PATCH http://localhost:3000/api/tasks/fdfebb28-9eeb-4e3f-84b8-0e271051f3ac/status
Content-Type: application/json

{
  "status": "done"
}

### Register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password123"
}

### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password123"
}

### Production - Get all tasks
GET https://task-tracker-production-2a51.up.railway.app/api/tasks